#!/usr/bin/env bash
# Script that displays information about subdomains

# Define function that returns destination and record about it subdomain

get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        # No subdomain provided, display information fro default subdomains
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        # Subdomain provided display information for the specified subdomain
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        # Perform dig command and process output using awk
        echo "$(dig $sub.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$sub"' is a "$4" record and points to "$5}')"

    done
}

get_subdomain_info "$1" "$2"
