#!/usr/bin/env bash
# Haproxy SSL termination
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    ssl-dh-param-file /etc/haproxy/dhparams.pem

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    bind *:443 ssl crt /etc/haproxy/certs/www.ackerm.tech.pem
    redirect scheme https code 301 if !{ ssl_fc }
    default_backend servers

backend servers
    balance roundrobin
    server web-01 18.207.207.202:80 check
    server web-02 18.207.112.121:80 check
