#!/usr/bin/env bash

#script to transfer a file to a server
#Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
