#!/usr/bin/env bash
# Script to install nginx on server


sudo apt update
sudo apt-get -y install nginx

sudo chown -R "$USER":"$USER" /var/www/html

sudo echo 'Hello World!' > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
sudo service nginx reload