#!/usr/bin/env bash
# Script to install nginx on server


sudo apt update
sudo apt-get -y install nginx

sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo rm /etc/nginx/sites-enabled/default
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
}'
sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
sudo service nginx reload
