#!/usr/bin/env bash
# nginx & 301

sudo apt update
sudo apt-get -y instal nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html

# configure the redirection
sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo rm /etc/nginx/sites-enabled/default

echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.perplexity.ai/
    }
}' > /etc/nginx/sites-enabled/default


#if the test is succesful, reload nginx to apply the changes
sudo service nginx restart   
sudo service nginx reload