#!/usr/bin/env bash
# nginx & 301

sudo apt update
sudo apt -y install nginx

# configure the redirection
sudo bash -c 'echo "server {
    lister 80;
    server_name ackerm.tech;

    location /redirect_me {
        return 301 https://perplexity.ai;
    }
}" > /etc/nginx/sites-available/redirect.conf'

# create symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/

#test the nginx configuration
sudo nginx -t

#if the test is succesful, reload nginx to apply the changes   
sudo systemctl reload nginx