#!/usr/bin/env bash
# A script

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html

# Configure redirection
sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo rm /etc/nginx/sites-enabled/default
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
            return 301 https://www.google.com;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-enabled/default

# Configure 404
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Restart
sudo service nginx restart
sudo service nginx reload
