#!/usr/bin/env bash
#Install haproxy

#update the system
sudo apt update
sudo apt upgrade -y

#Install HAproxy
sudo apt install -y haproxy

#configure Haproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo touch /etc/haproxy/haproxy.cfg

#Bulid the haproxy configuration file
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    deamon

default
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 251432-web-01:80 check
    server web-02 251432-web-02:80 check
EOT

#Enable Haproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

#Restart HAproxy service
sudo service haproxy restart

