#!/usr/bin/env bash
#script to install ufw

sudo apt-get install ufw

#block incoming traffic
sudo ufw default deny incoming

#allow traffic from some ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw --force enable
