#!/usr/bin/env bash
# /api on 5002

server {

        add_header X-Served-By 251432-web-01;
        listen 80;
        listen [::]:80;

        root /var/www/html;
        index index.html, index.htm, index.nginx-debian.html;


        server_name _;

        location / {
        try_files $uri $uri/ @404;
        }

        location /airbnb-onepage {
                proxy_pass http://127.0.0.1:5000/airbnb-onepage;
                proxy_redirect off;
                proxy_set_header Host $host;
        }

        location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://localhost:5001/number_odd_or_even/;
        proxy_redirect off;
        }

        location /api/ {
                proxy_pass http://localhost:5002/api/;
                proxy_redirect off;
        }

        location /redirect_me {
        return 301 https://www.perpelexity.ai/;
        }


        error_page 404 /404.html;
        location = /404.html {
        return 404 "It is a dead end, let's go back\n";
    }
}